### ISSUE TITLE
sample1

### ISSUE THREAD

**Issue by tkg-reis** [tkg-reis/working-holiday-calc-app#23]
```yaml
start_date: 2024/7/1
due_date: 2024/6/30
progress: 0.1
parent: 0
```
