### ISSUE TITLE
sample02

### ISSUE THREAD

**Issue by tkg-reis** [tkg-reis/working-holiday-calc-app#24]
```yaml
start_date: 2024/7/13
due_date: 2024/7/13
progress: 0.1
parent: 0
```
